# Generated by Django 5.0.2 on 2024-04-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sand', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('Bricks', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('descrption', models.CharField(default='desc', max_length=100)),
                ('to', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('cateogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpManager.category')),
            ],
        ),
    ]
