# Generated by Django 5.0.2 on 2024-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Bricks',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sand',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=100, unique=True),
        ),
    ]
